### ISSUE TITLE
Issue in running LISFLOOD calibration for the basin reg.

### ISSUE THREAD

**Issue by diksha922** [ec-jrc/lisflood-calibration#13]
Hello @StefaniaGrimaldi.

Thank you for guiding me to run the basic LISFLOOD model.

Now, I am trying to run the lisflood calibration for the Tapi basin to calibrate the basin with the observed streamflow at the gauging site.
 
I am following the steps mentioned on the web to install and run lisflood calibration. However, I am unable to run the calibration tool for the basin. 

The steps mentioned in the portal are not clear to me. Even I am not getting the sequence of steps to run the lisflood calibration.

Is there a requirement to create an environment?

Please guide me to understand the step-by-step process.

Thanks & Regards,

Diksha Gupta

**Comment by StefaniaGrimaldi** [comment]
Dear @diksha922,

it is great to know that you were able to run OS LISFLOOD for the Tapi catchment!

Regarding the calibration tool, we are working on an extensive revision of the documentation. You might be interested in the _working_ document:
[calibtool_instructions_working_document.docx](https://github.com/user-attachments/files/16254384/calibtool_instructions_working_document.docx)

Furthermore, we recommend consulting this issue: https://github.com/ec-jrc/lisflood-calibration/issues/7 

We will do our best to reply to specific questions regarding the execution of the various steps.

Kind regards,
on behalf of the developers team,
Stefania

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi,

I am working on the calibration of the Tapi basin. I cannot create the "station_data.csv" and "station_link.csv" files for the Tapi basin. Can you please help me with this?

Thanks & Regards,

Diksha Gupta

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi .

Any updates on the above issue?

**Comment by StefaniaGrimaldi** [comment]
Dear @diksha922,

station_link.csv is generate by https://github.com/ec-jrc/lisflood-calibration/blob/master/bin/CAL_3_PREP_MISC.py.
You can find an example of station_link.csv here https://github.com/ec-jrc/lisflood-calibration/blob/master/tests/data/stations_links.csv 

Please note that in order to run https://github.com/ec-jrc/lisflood-calibration/blob/master/bin/CAL_3_PREP_MISC.py 
you must first complete the previous steps of the calibration tool. 

This issue https://github.com/ec-jrc/lisflood-calibration/issues/7 provides useful information.

Kind regards,
Stefania

**Comment by StefaniaGrimaldi** [comment]
Dear @diksha922,

thank you for your kind suggestions on how to improve the documentation and the user guide for the calibration tool. Unfortunately, at the moment we are all busy with operational tasks, we will follow up on your suggestions as early as possible, in 2025.
Nevertheless, we are aware that other users successfully completed the calibration for their case study by following the information already available (see my answers above).
For instance, the first step is explained into detail here https://github.com/ec-jrc/lisflood-calibration/issues/7#issuecomment-1210445292 : this message explains the input argument to the python code.

Kind regards,
Stefania

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi Mam.

I have worked on the steps mentioned for the calibration of LISFLOOD model, however, I am getting the following errors:

(base) diksha@diksha-VirtualBox:~/Documents/LISFLOOD/lisflood-calibration$ python ./bin/CAL_1_FILTER_STATIONS.py ./tapi/settings_tapi.txt ./tapi/station_data.csv T
=================== START ===================
Settings:
- Main
  - forcing_start: 02/01/1979 00:00
  - forcing_end: 31/12/2012 00:00
  - timestep: 1440
  - prerun_start: PRERUN_STARTDATE
  - prerun_end: 31/12/2012 00:00
  - prerun_timestep: 1440
  - fast_debug: 0
  - min_obs_years: 3.5
- Stations
  - stations_data: ./stations_data.csv
  - stations_links: ./stations_links.csv
  - observed_discharges: OBS
- CSV
  - qgis: ./stations_data.csv
  - qtss: ./observations.csv
- Path
  - param_ranges: ./param_ranges.csv
  - subcatchment_path: CATCHMENTS_DIR
  - summary_path: SUMMARY_DIR
- Templates
  - lisfloodsettings: ./settings_tapi-PreRun.xml
- DEAP
  - numcpus: NCPUS
  - min_gen: 8
  - max_gen: 24
  - mu: 16
  - lambda_: 32
  - pop: 64
  - gen_offset: 3
  - effmax_tol: 0.003
Reading input stations data ./tapi/station_data.csv
                                       4501
ObsID                                      
StationName                       Borgotaro
Provider ID                            1016
Country code                             IT
StationLat                        44.514057
StationLon                          9.84219
Height                                  354
Height Units                              m
DrainingArea.km2.Provider                 -
Catchment Area Units                    km2
Added Date                 18-09-2012 19:00
River                                  Taro
Catchment                                Po
EC_Catchments                            Po
Calibration ID                            -
DrainingArea.km2.LDD                    400
LisfloodX                           4307500
LisfloodY                           2377500
RealTime                              FALSE
PostProcess                           FALSE
FixedRepPoint                          TRUE
HasWL                                     1
HasD                                      0
Alive D                                   1
StartDate_hist_24          21-09-2006 00:00
EndDate_hist_24            01-07-2008 00:00
StartDate_nrt_24           09-05-2012 00:00
EndDate_nrt_24             08-11-2017 00:00
StartDate_hist_6           20-09-2006 18:00
EndDate_hist_6             01-07-2008 00:00
StartDate_nrt_6            08-05-2012 12:00
EndDate_nrt_6              07-11-2017 12:00
DiffDays_hist_24                        649
DiffDays_nrt_24                        2009
DiffDays_hist_6                         649
DiffDays_nrt_6                         2009
cal_hist_24h                          FALSE
cal_nrt_24h                            TRUE
cal_hist_6h                           FALSE
cal_nrt_6h                             TRUE
CAL_TYPE                             NRT_6h
Notes                                     -
EC_calib                                  T
Dam/Lake                                  -
EnoughQdata                               1
Val_Start                  08-05-2012 12:00
Val_End                    02-01-2012 06:00
Cal_Start                  31-12-2016 06:00
Cal_End                    31-12-2017 06:00
CatchmentArea                            16
SamplingFrequency                         2
Spinup_days                              30
Obs_start                  30-01-2017 12:00
Obs_end                    31-12-2017 06:00
Split_date                 30-01-2017 12:00
N_data                                 1341
Traceback (most recent call last):
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EC_calib'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/diksha/Documents/LISFLOOD/lisflood-calibration/./bin/CAL_1_FILTER_STATIONS.py", line 45, in <module>
    stations_meta = stations_meta[stations_meta['EC_calib'] >= int(args.stations_type)]
                                  ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EC_calib'
(base) diksha@diksha-VirtualBox:~/Documents/LISFLOOD/lisflood-calibration$ 

Kindly help me in correcting the same so that I can proceed further.

**Comment by StefaniaGrimaldi** [comment]
Dear @diksha922,

the error is due to the incorrect use of 'EC_calib'. Furthermore, the structure of the file stations.csv might not be correct.

I believe that the explanation provided here https://github.com/ec-jrc/lisflood-calibration/issues/7#issuecomment-1210445292 can help you to solve the issue. This message explains that the template of the file stations.csv can be found in the "integration" folder.

As a first step, I would carefully check the structure of the file stations.csv: you can refer to the example inside the "integration" folder, and to the example kindly provided by another OS LISFLOOD user: https://github.com/ec-jrc/lisflood-calibration/issues/7#issuecomment-1215067459 

When launching the script CAL_1_FILTER_STATIONS.py, stations_type is the filter applied to the list of stations included into the stations.csv file. Only the station that have "station_type" value lower or equal to the value in the "EC_calib" column will be processed. Please, set both "station_type" and "EC_calib" as numerical values, see, for instance, https://github.com/ec-jrc/lisflood-calibration/issues/7#issuecomment-1215067459.

I hope that this answer helps,
kind regards,
Stefania

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi Mam.

I have followed the steps mentioned in the issue #7 and able to run the code till step 2.

However, I am getting the following error while running the step 3:

base) diksha@diksha-VirtualBox:~/Documents/LISFLOOD/lisflood-calibration$ python ./bin/CAL_1_FILTER_STATIONS.py ./tapi/settings_tapi.txt ./tapi/stations.csv 0
=================== START ===================
Settings:
- Main
  - forcing_start: 08/05/2012 00:00
  - forcing_end: 31/12/2012 00:00
  - timestep: 1440
  - prerun_start: 01-01-2012 00:00
  - prerun_end: 31/12/2012 00:00
  - prerun_timestep: 1440
  - fast_debug: 0
  - min_obs_years: 3.5
- Stations
  - stations_data: ./tapi/stations.csv
  - stations_links: ./tapi/stations_links.csv
  - observed_discharges: ./tapi/observations.csv
- CSV
  - qgis: ./tapi/stations.csv
  - qtss: ./tapi/observations.csv
- Path
  - param_ranges: ./param_ranges.csv
  - subcatchment_path: CATCHMENTS_DIR
  - summary_path: SUMMARY_DIR
- Templates
  - lisfloodsettings: ./settings_tapi-PreRun.xml
- DEAP
  - numcpus: NCPUS
  - min_gen: 8
  - max_gen: 24
  - mu: 16
  - lambda_: 32
  - pop: 64
  - gen_offset: 3
  - effmax_tol: 0.003
Reading input stations data ./tapi/stations.csv
               StationName  Provider ID  ... CatchmentArea  SamplingFrequency
ObsID                                    ...                                 
380              Borgotaro         1016  ...          16.0                2.0
2733         Raskov Morava         1062  ...          17.0                1.0
2730             Bejanovo          1062  ...          18.0                1.0
1976               KEMPTEN         1062  ...          38.0                2.0
2910   VILLAFRANCA PELLICE         1062  ...          40.0                2.0
287              Chmelnica         1018  ...          53.0                2.0
2824               Fossano         1062  ...          56.0                2.0
428            San Secondo         1016  ...          58.0                1.0
2822            Farigliano         1062  ...          58.0                2.0
892              Wiblingen         1025  ...          92.0                1.0
2787             Carignano         1062  ...         153.0                1.0
2823                  Asti         1062  ...         179.0                1.0
817                Kormend         1017  ...         191.0                1.0
492                  ŻABNO         1024  ...         276.0                1.0
4501           Sarangkheda         1024  ...           NaN                NaN

[15 rows x 53 columns]
Found 1 calibration stations to check
Found 1 valid calibration stations
       StationName  Provider ID  ... CatchmentArea  SamplingFrequency
ObsID                            ...                                 
4501   Sarangkheda         1024  ...           NaN                NaN

[1 rows x 53 columns]
==================== END ====================
(base) diksha@diksha-VirtualBox:~/Documents/LISFLOOD/lisflood-calibration$ python ./bin/CAL_2_SET_PRERUN_IN_SETTINGS.py ./tapi/settings_tapi.txt ./tapi/stations.csv 4501
=================== START ===================
Reading input stations data ./tapi/stations.csv
       StationName  Provider ID  ... CatchmentArea  SamplingFrequency
ObsID                            ...                                 
4501   Sarangkheda         1024  ...           NaN                NaN

[1 rows x 53 columns]
(base) diksha@diksha-VirtualBox:~/Documents/LISFLOOD/lisflood-calibration$ python ./bin/CAL_3_PREP_MISC.py ./tapi/settings_tapi.txt ./home/diksha/Documents/LISFLOOD/lisflood-code/tests/data/tapi/maps/ldd.nc ./tapi/stations.txt ./tapi/
=================== START ===================
>> Reading stations data csv file...
>> Make map with station locations (outlet.map)...
Traceback (most recent call last):
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'LisfloodX'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/diksha/Documents/LISFLOOD/lisflood-calibration/./bin/CAL_3_PREP_MISC.py", line 58, in <module>
    f.write(str(row['LisfloodX']) + " ")
                ~~~^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'LisfloodX'
(base) diksha@diksha-VirtualBox:~/Documents/LISFLOOD/lisflood-calibration$ python ./bin/CAL_3_PREP_MISC.py ./tapi/settings_tapi.txt ./home/diksha/Documents/LISFLOOD/lisflood-code/tests/data/tapi/maps/ldd.nc ./tapi/stations.txt ./tapi/

=================== START ===================
>> Reading stations data csv file...
>> Make map with station locations (outlet.map)...
Traceback (most recent call last):
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'LisfloodX'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/diksha/Documents/LISFLOOD/lisflood-calibration/./bin/CAL_3_PREP_MISC.py", line 58, in <module>
    f.write(str(row['LisfloodX']) + " ")
                ~~~^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'LisfloodX'

I have also attached herewith the screenshot of the stations.csv file.

Kindly help me in this.

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi, @doc78, @domeniconappo,

Any update on the above mentioned issue.

**Comment by StefaniaGrimaldi** [comment]
Dear @diksha922,

please find here the instructions on how to solve the error "wrong input mask file": 
https://github.com/ec-jrc/lisflood-calibration/issues/7#issuecomment-1230031178 

CAL_6_CUT_MAPS.py requires a valid "mask.map" pcraster file. 

We hope this answer helps,
kind regards,
Stefania

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi,

I have prepared the file structure same as mentioned in the issue #7. However, still I am facing the same issue.

The screenshot of the file structure and log error is attached for reference.

**Comment by StefaniaGrimaldi** [comment]
Hi @diksha922,

does this screenshot https://private-user-images.githubusercontent.com/47293688/400206801-f2e90176-81f3-46ee-a75e-b3aa2da631db.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NDcyNDEsIm5iZiI6MTczNjQ0Njk0MSwicGF0aCI6Ii80NzI5MzY4OC80MDAyMDY4MDEtZjJlOTAxNzYtODFmMy00NmVlLWE3NWUtYjNhYTJkYTYzMWRiLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE4MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZjBmZTY1OGJhYzBhN2M2YmUwYWI0ZDBlMzA5MDMyZWZmMzlmMjViNjhmMjFkMzFhZmZiMGMyYWViZjIwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fpgc34KtE6pSr85QG9LQwSIHK-0GB2C8kvg_jWOjmfM shows the folder including the "large" maps from which you would like to generate the cut-out?

Could you please confirm that you were able to run https://github.com/ec-jrc/lisflood-calibration/blob/master/bin/CAL_5_PREP_FORCING.py successfully? If that is the case, you should see a folder "4501" including the subfolders "maps", "inflow", "out".

Stefania

**Comment by diksha922** [comment]
Hello @StefaniaGrimaldi Mam.

Thank you Mam for the response.

I have checked the folder "4501", it contains only station sub-folder (screenshot attached).

The folder I have prepared for tapi and corresponding files created after running till step CAL_5 is also attached herewith for ready reference.

Kindly help me in this please.
![Capturen](https://github.com/user-attachments/assets/2653feb5-7649-493d-a837-6f4265d03c6c)

**Comment by StefaniaGrimaldi** [comment]
Dear @diksha922,

there are some errors in the folder structure and in the files: these errors indicate that some of the steps were not perfomed correctly.

Having considered these difficulties, I strongly recommend proceeding as follows: perform the calibration of one single single headcatchment to learn the correct structures of files and folder. 

For this purpose, you should select one headcatchment in your model domain and identify the coordinates of the calibration station on the LISFLOOD local drainage direction map (ldd). The coordinate values in your file stations.txt file should be consistent with your ldd map (you can find examples for the 3arcmin ldd in https://global-flood.emergency.copernicus.eu/glofas-forecasting/)
![image](https://github.com/user-attachments/assets/b96b4091-8502-436b-8496-fa678805bf0a)

The coordindates of the calibration station must then be used to prepare the cut-out of the LISFLOOD maps (meteorological forcings and static maps) for your headcatchment.

This 
[folder_structure.zip](https://github.com/user-attachments/files/18389448/folder_structure.zip)
should help you prepare the structure of your calibration folder.

Please create a subfolder for your headacatchment. In the attached example, you see bogus numbers such as 1002, please use the ID of your headcatchment station. 
Such headcatchment folder must have a subfolder "maps" including the cut-out of the LISFLOOD maps (meteorological forcings and static maps) for your headcatchment.

The CUTMAPS tool allows you to prepare the cutout: please follow the instructions here https://github.com/ec-jrc/lisflood-utilities?tab=readme-ov-file#cutmaps 
cutmaps -f YOUR_INPUT_FOLDER -l YOUR_LDD_MAP -N coordinates_calib_station.txt -o YOUR_OUTPUT_FOLDER
YOUR_INPUT_FOLDER = the folder where your save all the maps for the extended domain
YOUR_LDD_MAP = path leading to the ldd of your set-up
coordinates_calib_station.txt = please see the format explained in https://github.com/ec-jrc/lisflood-utilities?tab=readme-ov-file#cutmaps 
YOUR_OUTPUT_FOLDER = the sub-folder "maps" mentioned above.

Please have a look at the attached folder_structure and prepare the cut-out of the maps, as well as the "stations" sub-folder.

As soon as data, maps, templates, settings are all in the correct format, you will only need to run CAL_7A and CAL_7B to complete the calibration of your headcatchment!

One final, side note on your data: I noticed that the observations have 6hours steps. Are your planning to run LISFLOOD at 6h steps (with 6h forcings)?

I hope that this answer helps,
kind regards,
Stefania
